security:
    always_authenticate_before_granting: true

    # Set up our custom md5 encoder for the password
    encoders:
        DOMjudge\MainBundle\Entity\User:
            id: md5_encoder

    role_hierarchy:
        # Admin role has all other roles
        ROLE_ADMIN: [ROLE_JURY, ROLE_TEAM, ROLE_BALLOON, ROLE_PRINT, ROLE_JUDGEHOST, ROLE_EVENT_READER, ROLE_FULL_EVENT_READER]

    providers:
        dj_db_provider:
            entity:
                class: DOMjudgeMainBundle:User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path:                     login
                check_path:                     login_check
                username_parameter:             login[username]
                password_parameter:             login[password]
                csrf_parameter:                 login[_token]
                csrf_token_id:                  authenticate
                csrf_token_generator:           security.csrf.token_manager
            provider: dj_db_provider
            logout:
                path: logout
                target: /

    # Set up default authentication for admin and team pages
    access_control:
        -
            path: ^/jury
            allow_if: "has_role('ROLE_JURY') or has_role('ROLE_BALLOON')"
        -
            path: ^/team
            roles: ROLE_TEAM
