DOMjudge\MainBundle\Entity\Clarification:
    type: entity
    table: clarification
    indexes:
        respid:
            columns:
                - respid
        probid:
            columns:
                - probid
        cid:
            columns:
                - cid
        cid_2:
            columns:
                - cid
                - answered
                - submittime
    id:
        clarid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        submitTime:
            type: decimal
            nullable: false
            precision: 32
            scale: 9
            comment: 'Time sent'
            column: submittime
        sender:
            type: integer
            nullable: true
            unsigned: true
            comment: 'Team ID, null means jury'
        recipient:
            type: integer
            nullable: true
            unsigned: true
            comment: 'Team ID, null means to jury or to all'
        juryMember:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: 'Name of jury member who answered this'
            column: jury_member
        category:
            type: string
            nullable: true
            length: 128
            fixed: false
            comment: 'Category associated to this clarification; only set for non problem clars'
        body:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: 'Clarification text'
        answered:
            type: boolean
            nullable: false
            comment: 'Has been answered by jury?'
            default: '0'
    manyToOne:
        contest:
            targetEntity: Contest
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: cid
            orphanRemoval: false
        inReplyTo:
            targetEntity: Clarification
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                respid:
                    referencedColumnName: clarid
            orphanRemoval: false
        problem:
            targetEntity: Problem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                probid:
                    referencedColumnName: probid
            orphanRemoval: false
    manyToMany:
        unreadTeams:
            targetEntity: Team
            cascade: {  }
            mappedBy: unreadClarifications
            inversedBy: null
            joinTable: null
            orderBy: null
    oneToMany:
        responses:
            targetEntity: Clarification
            mappedBy: inReplyTo
            inversedBy: inReplyTo
        events:
            targetEntity: Event
            mappedBy: clarification
            inversedBy: clarification
    lifecycleCallbacks: {  }
