DOMjudge\MainBundle\Entity\Contest:
    type: entity
    table: contest
    indexes:
        cid:
            columns:
                - cid
                - enabled
    uniqueConstraints:
        shortname:
            columns:
                - shortname
    id:
        cid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Descriptive name'
        shortName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Short name for this contest'
            column: shortname
        activateTime:
            type: decimal
            nullable: false
            precision: 32
            scale: 9
            comment: 'Time contest becomes visible in team/public views'
            column: activatetime
        startTime:
            type: decimal
            nullable: false
            precision: 32
            scale: 9
            comment: 'Time contest starts, submissions accepted'
            column: starttime
        freezeTime:
            type: decimal
            nullable: true
            precision: 32
            scale: 9
            comment: 'Time scoreboard is frozen'
            column: freezetime
        endTime:
            type: decimal
            nullable: false
            precision: 32
            scale: 9
            comment: 'Time after which no more submissions are accepted'
            column: endtime
        unfreezeTime:
            type: decimal
            nullable: true
            precision: 32
            scale: 9
            comment: 'Unfreeze a frozen scoreboard at this time'
            column: unfreezetime
        deactivateTime:
            type: decimal
            nullable: true
            precision: 32
            scale: 9
            comment: 'Time contest becomes invisible in team/public views'
            column: deactivatetime
        activateTimeString:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: 'Authoritative absolute or relative string representation of activatetime'
            column: activatetime_string
        startTimeString:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: 'Authoritative absolute (only!) string representation of starttime'
            column: starttime_string
        freezeTimeString:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: 'Authoritative absolute or relative string representation of freezetime'
            column: freezetime_string
        endTimeString:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: 'Authoritative absolute or relative string representation of endtime'
            column: endtime_string
        unfreezeTimeString:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: 'Authoritative absolute or relative string representation of unfreezetrime'
            column: unfreezetime_string
        deactivateTimeString:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: 'Authoritative absolute or relative string representation of deactivatetime'
            column: deactivatetime_string
        enabled:
            type: boolean
            nullable: false
            comment: 'Whether this contest can be active'
            default: '1'
        processBalloons:
            type: boolean
            nullable: true
            comment: 'Will balloons be processed for this contest?'
            default: '1'
            column: process_balloons
        public:
            type: boolean
            nullable: true
            comment: 'Is this contest visible for the public and non-associated teams?'
            default: '1'
    manyToMany:
        problems:
            targetEntity: Problem
            cascade: {  }
            mappedBy: null
            inversedBy: contests
            joinTable:
                name: contestproblem
                joinColumns:
                    -
                        name: cid
                        referencedColumnName: cid
                inverseJoinColumns:
                    -
                        name: probid
                        referencedColumnName: probid
            orderBy: null
        teams:
            targetEntity: Team
            cascade: {  }
            mappedBy: contests
            inversedBy: null
            joinTable: null
            orderBy: null
    oneToMany:
        auditlogs:
            targetEntity: AuditLog
            mappedBy: contest
            inversedBy: contest
        clarifications:
            targetEntity: Clarification
            mappedBy: contest
            inversedBy: contest
        events:
            targetEntity: Event
            mappedBy: contest
            inversedBy: contest
        judgings:
            targetEntity: Judging
            mappedBy: contest
            inversedBy: contest
        submissions:
            targetEntity: Submission
            mappedBy: contest
            inversedBy: contest
    lifecycleCallbacks: {  }
