DOMjudge\MainBundle\Entity\Judging:
    type: entity
    table: judging
    indexes:
        submitid:
            columns:
                - submitid
        judgehost:
            columns:
                - judgehost
        cid:
            columns:
                - cid
        rejudgingid:
            columns:
                - rejudgingid
        prevjudgingid:
            columns:
                - prevjudgingid
    id:
        judgingid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startTime:
            type: decimal
            nullable: false
            precision: 32
            scale: 9
            comment: 'Time judging started'
            column: starttime
        endTime:
            type: decimal
            nullable: true
            precision: 32
            scale: 9
            comment: 'Time judging ended, null = still busy'
            column: endtime
        result:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: 'Result string as defined in config.php'
        verified:
            type: boolean
            nullable: false
            comment: 'Result verified by jury member?'
            default: '0'
        juryMember:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: 'Name of jury member who verified this'
            column: jury_member
        verifyComment:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Optional additional information provided by the verifier'
            column: verify_comment
        valid:
            type: boolean
            nullable: false
            comment: 'Old judging is marked as invalid when rejudging'
            default: '1'
        outputCompile:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Output of the compiling the program'
            column: output_compile
        seen:
            type: boolean
            nullable: false
            comment: 'Whether the team has seen this judging'
            default: '0'
    manyToOne:
        contest:
            targetEntity: Contest
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: cid
            orphanRemoval: false
        submission:
            targetEntity: Submission
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                submitid:
                    referencedColumnName: submitid
            orphanRemoval: false
        judgehost:
            targetEntity: Judgehost
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                judgehost:
                    referencedColumnName: hostname
            orphanRemoval: false
        rejudging:
            targetEntity: Rejudging
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rejudgingid:
                    referencedColumnName: rejudgingid
            orphanRemoval: false
        previousJudging:
            targetEntity: Judging
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                prevjudgingid:
                    referencedColumnName: judgingid
            orphanRemoval: false
    oneToMany:
        events:
            targetEntity: Event
            mappedBy: judging
            inversedBy: judging
        nextJudgings:
            targetEntity: judging
            mappedBy: previousJudging
            inversedBy: previousJudging
        judgingRuns:
            targetEntity: judgingRun
            mappedBy: judging
            inversedBy: judging
    lifecycleCallbacks: {  }
