DOMjudge\MainBundle\Entity\JudgingRun:
    type: entity
    table: judging_run
    indexes:
        judgingid:
            columns:
                - judgingid
        testcaseid_2:
            columns:
                - testcaseid
    uniqueConstraints:
        testcaseid:
            columns:
                - judgingid
                - testcaseid
    id:
        runid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        runResult:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: 'Result of this run, NULL if not finished yet'
            column: runresult
        runTime:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: 'Submission running time on this testcase'
            column: runtime
        outputRun:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Output of running the program'
            column: output_run
        outputDiff:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Diffing the program output and testcase output'
            column: output_diff
        outputError:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Standard error output of the program'
            column: output_error
        outputSystem:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Judging system output'
            column: output_system
    manyToOne:
        testcase:
            targetEntity: Testcase
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                testcaseid:
                    referencedColumnName: testcaseid
            orphanRemoval: false
        judging:
            targetEntity: Judging
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                judgingid:
                    referencedColumnName: judgingid
            orphanRemoval: false
    lifecycleCallbacks: {  }
