DOMjudge\MainBundle\Entity\Language:
    type: entity
    table: language
    id:
        langid:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: 'Unique ID (string)'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Descriptive language name'
        extensions:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'List of recognized extensions (JSON encoded)'
        allowSubmit:
            type: boolean
            nullable: false
            comment: 'Are submissions accepted in this language?'
            default: '1'
            column: allow_submit
        allowJudge:
            type: boolean
            nullable: false
            comment: 'Are submissions in this language judged?'
            default: '1'
            column: allow_judge
        timeFactor:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: 'Language-specific factor multiplied by problem run times'
            default: '1'
            column: time_factor
        compileScript:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: 'Script to compile source code for this language'
            column: compile_script
    lifecycleCallbacks: {  }
