DOMjudge\MainBundle\Entity\Problem:
    type: entity
    table: problem
    id:
        probid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Descriptive name'
        timeLimit:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Maximum run time for this problem'
            default: '0'
            column: timelimit
        memLimit:
            type: integer
            nullable: true
            unsigned: true
            comment: 'Maximum memory available (in kB) for this problem'
            column: memlimit
        outputLimit:
            type: integer
            nullable: true
            unsigned: true
            comment: 'Maximum output size (in kB) for this problem'
            column: outputlimit
        specialRun:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: 'Script to run submissions for this problem'
            column: special_run
        specialCompare:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: 'Script to compare problem and jury output for this problem'
            column: special_compare
        specialCompareArgs:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Optional arguments to special_compare script'
            column: special_compare_args
        problemText:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Problem text in HTML/PDF/ASCII'
            column: problemtext
        problemTextType:
            type: string
            nullable: true
            length: 4
            fixed: false
            comment: 'File type of problem text'
            column: problemtext_type
    manyToMany:
        contests:
            targetEntity: Contest
            cascade: {  }
            mappedBy: problems
            inversedBy: null
            joinTable: null
            orderBy: null
    oneToMany:
        clarifications:
            targetEntity: Clarification
            mappedBy: problem
            inversedBy: problem
        events:
            targetEntity: Event
            mappedBy: problem
            inversedBy: problem
        submissions:
            targetEntity: Submission
            mappedBy: problem
            inversedBy: problem
        testcases:
            targetEntity: TestCase
            mappedBy: problem
            inversedBy: problem
    lifecycleCallbacks: {  }
