DOMjudge\MainBundle\Entity\RankCachePublic:
    type: entity
    table: rankcache_public
    indexes:
        order:
            columns:
                - cid
                - points
                - totaltime
    id:
        cid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Contest ID'
            id: true
        teamid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Team ID'
            id: true
    fields:
        points:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Total correctness points'
            default: '0'
        totalTime:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Total time spent'
            default: '0'
            column: totaltime
    manyToOne:
        # We have no reverse for this, as this does not make any sense
        contest:
            targetEntity: Contest
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: cid
            orphanRemoval: false
        team:
            targetEntity: Team
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                teamid:
                    referencedColumnName: teamid
            orphanRemoval: false
    lifecycleCallbacks: {  }
