DOMjudge\MainBundle\Entity\ScoreCachePublic:
    type: entity
    table: scorecache_public
    id:
        cid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Contest ID'
            id: true
        teamid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Team ID'
            id: true
        probid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Problem ID'
            id: true
    fields:
        submissions:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Number of submissions made'
            default: '0'
        pending:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Number of submissions pending judgement'
            default: '0'
        totalTime:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Total time spent'
            default: '0'
            column: totaltime
        isCorrect:
            type: boolean
            nullable: false
            comment: 'Has there been a correct submission?'
            default: '0'
            column: is_correct
    manyToOne:
        contest:
            targetEntity: Contest
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: cid
            orphanRemoval: false
        team:
            targetEntity: Team
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                teamid:
                    referencedColumnName: teamid
            orphanRemoval: false
        problem:
            targetEntity: Problem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                probid:
                    referencedColumnName: probid
            orphanRemoval: false
    lifecycleCallbacks: {  }
