DOMjudge\MainBundle\Entity\Submission:
    type: entity
    table: submission
    indexes:
        teamid:
            columns:
                - cid
                - teamid
        judgehost:
            columns:
                - cid
                - judgehost
        teamid_2:
            columns:
                - teamid
        probid:
            columns:
                - probid
        langid:
            columns:
                - langid
        judgehost_2:
            columns:
                - judgehost
        origsubmitid:
            columns:
                - origsubmitid
        rejudgingid:
            columns:
                - rejudgingid
        IDX_DB055AF34B30D9C4:
            columns:
                - cid
    id:
        submitid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        submittime:
            type: decimal
            nullable: false
            precision: 32
            scale: 9
            comment: 'Time submitted'
        valid:
            type: boolean
            nullable: false
            comment: 'If false ignore this submission in all scoreboard calculations'
            default: '1'
        expectedResults:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'JSON encoded list of expected results - used to validate jury submissions'
            column: expected_results
    manyToOne:
        cid:
            targetEntity: Contest
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: cid
            orphanRemoval: false
        teamid:
            targetEntity: Team
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                teamid:
                    referencedColumnName: teamid
            orphanRemoval: false
        probid:
            targetEntity: Problem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                probid:
                    referencedColumnName: probid
            orphanRemoval: false
        langid:
            targetEntity: Language
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                langid:
                    referencedColumnName: langid
            orphanRemoval: false
        judgehost:
            targetEntity: Judgehost
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                judgehost:
                    referencedColumnName: hostname
            orphanRemoval: false
        origsubmitid:
            targetEntity: Submission
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                origsubmitid:
                    referencedColumnName: submitid
            orphanRemoval: false
        rejudgingid:
            targetEntity: Rejudging
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rejudgingid:
                    referencedColumnName: rejudgingid
            orphanRemoval: false
    lifecycleCallbacks: {  }
