DOMjudge\MainBundle\Entity\TeamAffiliation:
    type: entity
    table: team_affiliation
    id:
        affilid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        shortName:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: 'Short descriptive name'
            column: shortname
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Descriptive name'
        country:
            type: string
            nullable: true
            length: 3
            fixed: true
            comment: 'ISO 3166-1 alpha-3 country code'
        comments:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: Comments
    oneToMany:
        teams:
            targetEntity: Team
            mappedBy: affiliation
            inversedBy: affiliation
    lifecycleCallbacks: {  }
