DOMjudge\MainBundle\Entity\Team:
    type: entity
    table: team
    indexes:
        affilid:
            columns:
                - affilid
        categoryid:
            columns:
                - categoryid
    uniqueConstraints:
        externalid:
            columns:
                - externalid
    id:
        teamid:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Unique ID'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        externalId:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Team ID in an external system'
            column: externalid
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Team name'
        enabled:
            type: boolean
            nullable: false
            comment: 'Whether the team is visible and operational'
            default: '1'
        members:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Team member names (freeform)'
        room:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: 'Physical location of team'
        comments:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Comments about this team'
        judgingLastStarted:
            type: decimal
            nullable: true
            precision: 32
            scale: 9
            comment: 'Start time of last judging for priorization'
            column: judging_last_started
        teampageFirstVisited:
            type: decimal
            nullable: true
            precision: 32
            scale: 9
            comment: 'Time of first teampage view'
            column: teampage_first_visited
        hostName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Teampage first visited from this address'
            column: hostname
        penalty:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Additional penalty time in minutes'
            default: '0'
    manyToOne:
        category:
            targetEntity: TeamCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoryid:
                    referencedColumnName: categoryid
            orphanRemoval: false
        affiliation:
            targetEntity: TeamAffiliation
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                affilid:
                    referencedColumnName: affilid
            orphanRemoval: false
    manyToMany:
        contests:
            targetEntity: Contest
            cascade: {  }
            mappedBy: null
            inversedBy: teams
            joinTable:
                name: contestteam
                joinColumns:
                    -
                        name: teamid
                        referencedColumnName: teamid
                inverseJoinColumns:
                    -
                        name: cid
                        referencedColumnName: cid
            orderBy: null
        unreadClarifications:
            targetEntity: Clarification
            cascade: {  }
            mappedBy: null
            inversedBy: unreadTeams
            joinTable:
                name: team_unread
                joinColumns:
                    -
                        name: teamid
                        referencedColumnName: teamid
                inverseJoinColumns:
                    -
                        name: mesgid
                        referencedColumnName: clarid
            orderBy: null
    oneToMany:
        submissions:
            targetEntity: Submission
            mappedBy: team
            inversedBy: team
        users:
            targetEntity: User
            mappedBy: team
            inversedBy: team
    lifecycleCallbacks: {  }
